### ISSUE TITLE
rows still selected after switching to the next page

### ISSUE THREAD

**Issue by NucsuM** [kmhgmbh/vue-md-powerful-datatable#2]
I select some rows.
If I switch to the next page, the selection in a line is still active.
But if I switch to the last page (with less items), only the last rows are selected.
Back to the first page (where I did the selection), the pagination works perfect on the other pages.

![issue02](https://user-images.githubusercontent.com/7623214/35325430-09313d9a-00f4-11e8-9f19-50a6f3653d1c.gif)

here is my main.vue:

[main.txt](https://github.com/kmhgmbh/vue-md-powerful-datatable/files/1659332/main.txt)

**Comment by marklabenski** [comment]
The problem seems to be the way the table rows are filtered. Instead of filtering via the "v-if" attribute the table should show a special array of all rows that have to be shown which is altered on every filter and search. 
Unfortunately that change will make an enormous refactoring necessary which I haven't got the time for right now. PRs are welcome 😉

**Comment by marklabenski** [comment]
Release 0.12.0 should have fixed that. I'd be happy to hear about your feedback

**Comment by NucsuM** [comment]
solved 👍
